/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2020;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

class DaySevenTest {
    @Test
    public void test() {
        String parseLine = DaySeven.parseLine("plaid fuchsia bags contain 5 light violet bags, 1 light yellow bag.");
        assertThat(parseLine).isEqualTo("plaid fuchsia");
    }
}
