/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2020;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class DayOne {

    public static void main(String[] args) throws IOException, URISyntaxException {
        Path path = Paths.get(DayOne.class.getClassLoader()
                .getResource("day_one.txt").toURI());
        List<String> lines = Files.readAllLines(path);

        for (int i = 0; i < lines.size(); i++) {
            for (int j = i + 1; j < lines.size(); j++) {
                int firstNumber = Integer.parseInt(lines.get(i));
                int secondNumber = Integer.parseInt(lines.get(j));
                if(firstNumber+secondNumber == 2020){
                    System.out.println(i + " " + j + firstNumber + " " + secondNumber + ": " + firstNumber * secondNumber);
//                    System.exit(0);
                }
            }
        }
    }
}
